# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT apfyt.wsgi:application

beta_settings:
    cloud_sql_instances: apfyt-fullstack-webapp:us-central1:sqlinstance-apfyt

runtime_config:
  python_version: 3
# [END runtime]
